### ISSUE TITLE
java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable on Ubuntu 22

### ISSUE THREAD

**Issue by kaszarobert** [kaszarobert/lando-restclient#1]
```
lando restclient
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:131)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
	at org.wiztools.restclient.ui.Main.main(Main.java:59)

```

Because 

```
echo $DISPLAY
:1
```

And in Landofile it is hardcoded to `:0`

**Comment by kaszarobert** [comment]
Fixed.
